# Sidebar navigation

- label: "Getting started"
  link: "/getting-started"
- label: "Courses"
  items:
    - label: "CSE101"
      link: "/courses/cse101"
    - label: "CSE102"
      link: "/courses/cse102"
    - label: "CSE114"
      link: "/courses/cse114"
    - label: "CSE215"
      link: "/courses/cse215"
    - label: "CSE216"
      link: "/courses/cse216"
    - label: "CSE220"
      link: "/courses/cse220"
    - label: "CSE300"
      link: "/courses/cse300"
    - label: "CSE304"
      link: "/courses/cse304"
    - label: "CSE305"
      link: "/courses/cse305"
    - label: "CSE306"
      link: "/courses/cse306"
    - label: "CSE307"
      link: "/courses/cse307"
    - label: "CSE308"
      link: "/courses/cse308"
    - label: "CSE310"
      link: "/courses/cse310"
    - label: "CSE312"
      link: "/courses/cse312"
    - label: "CSE316"
      link: "/courses/cse316"
    - label: "CSE320"
      link: "/courses/cse320"
    - label: "CSE323"
      link: "/courses/cse323"
    - label: "CSE327"
      link: "/courses/cse327"
    - label: "CSE351"
      link: "/courses/cse351"
    - label: "CSE352"
      link: "/courses/cse352"
    - label: "CSE353"
      link: "/courses/cse353"
    - label: "CSE373"
      link: "/courses/cse373"
    - label: "CSE416"
      link: "/courses/cse416"
    - label: "CSE475"
      link: "/courses/cse475"
    - label: "CSE487"
      link: "/courses/cse487"
- label: Community
  items:
    - label: "Github"
      link: https://github.com/computing-society/computer-science-resources
